In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report

In [8]:
#loading the dataset
data = pd.read_csv(r'E:\Users\Nirvan\Desktop\Projects\spam.csv' , encoding='latin1')

In [9]:
print(data.shape)

(5576, 5)

In [14]:
data.head()

  label                                         email_text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
data = data.rename(columns = {"v1":"label", "v2":"email_text"})

In [13]:
data = data.drop(columns = ["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"])

In [17]:
print(data['label'].value_counts())

ham     4828
spam     747
Spam       1
Name: label, dtype: int64

In [19]:
print(data.isnull().sum())

label         0
email_text    0
dtype: int64

In [20]:
data['label'] = data['label'].map({'ham':0, 'spam':1, 'Spam':1})

In [21]:
data.head()

   label                                         email_text
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [22]:
data = data[["email_text", "label"]]

In [23]:
data.head()

                                          email_text  label
0  Go until jurong point, crazy.. Available only ...      0
1                      Ok lar... Joking wif u oni...      0
2  Free entry in 2 a wkly comp to win FA Cup fina...      1
3  U dun say so early hor... U c already then say...      0
4  Nah I don't think he goes to usf, he lives aro...      0

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(data['email_text'], data['label'], test_size=0.2, random_state=0)

In [28]:
vectorizer = TfidfVectorizer(stop_words='english')
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

In [30]:
model = MultinomialNB()
model.fit(X_train_vectorized, Y_train)

MultinomialNB()

In [31]:
Y_pred = model.predict(X_test_vectorized)
print("accuracy: ", accuracy_score(Y_test, Y_pred))
print("classification report: ", classification_report(Y_test, Y_pred))

accuracy:  0.974910394265233
classification report:                precision    recall  f1-score   support

           0       0.97      1.00      0.99       979
           1       0.98      0.81      0.89       137

    accuracy                           0.97      1116
   macro avg       0.98      0.90      0.94      1116
weighted avg       0.98      0.97      0.97      1116

In [40]:
test_email = ["congratulations! You won a free holiday!"]
test_vectorized = vectorizer.transform(test_email)
prediction = model.predict(test_vectorized)
print("Prediction: ", "Spam" if prediction[0] == 1 else "Not spam")

Prediction:  Spam